spring:
  data:
    mongodb:
      host: 192.168.1.27
      port: 27017
      database: tron
      auto-index-creation: true

#----------logback---------------
logging:
  level:
    root: INFO
    org.tron: DEBUG

#----------L1---------------
cache:
  caffeine:
    enabled: true